name: reader_mode
description: A Dart port of Mozilla's Readability.js content extraction library.
version: 0.2.0
repository: https://github.com/mortezaPRK/readability
homepage: https://github.com/mortezaPRK/readability
issue_tracker: https://github.com/mortezaPRK/readability/issues

# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MPL-2.0
# See LICENSE file for details on dual licensing

topics:
  - html
  - parser
  - readability
  - content-extraction
  - article

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  html: ^0.15.5

dev_dependencies:
  coverage: ^1.8.0
  lints: 6.1.0
  test: ^1.25.0
