name: Publish to pub.dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish (e.g., v0.1.1). Leave empty to use latest tag."
        required: false
        type: string
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    environment: pub.dev
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ inputs.tag || github.ref }}
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
        with:
          sdk: stable
      - name: Publish
        run: dart pub publish --force
