name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.release.tag_name }}
      release_name: ${{ github.event.release.name }}
      prerelease: ${{ github.event.release.prerelease }}

  publish:
    name: Publish to pub.dev
    needs: build
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    environment: pub.dev
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
        with:
          sdk: stable
      - name: Publish
        run: dart pub publish --force
